title: Veronica Embroidery
description: Experts in embroidary & stitching in and around Koppa, NR Pura, Sringeri.
url: http://veronica.truejewels.com


sass:
  sass_dir: assets/css/_sass
  style: compressed



plugins:
  - jekyll-seo-tag